---
- hosts: all
  sudo: true
  tasks:
    - name: Install binaries
      yum: name={{ item }} state=latest
      with_items:
        - vim
        - git
        - wget
        - gcc
        - make
        - automake
        - autoconf
        - libtool
        - pcre
        - pcre-devel
        - libxml2
        - libxml2-devel
        - curl
        - curl-devel
        - httpd-devel
        - openssl-devel
    - name: Add nginx group
      group: name=nginx
    - name: Add nginx user
      user: name=nginx comment="Nginx web server" shell=/sbin/nologin home=/var/lib/nginx group=nginx
    - name: Download nginx
      get_url: url=http://nginx.org/download/nginx-1.8.0.tar.gz dest=/tmp
    - name: Uncompress nginx
      command: /bin/tar -xzf /tmp/nginx-1.8.0.tar.gz --directory=/root
    - name: Download naxsi
      get_url: url=https://github.com/nbs-system/naxsi/archive/0.54.tar.gz dest=/tmp
    - name: Uncompress naxsi
      command: /bin/tar -xzf /tmp/0.54.tar.gz --directory=/root
    - name: Compile nginx step 1
      command: ./configure --add-module=../naxsi-0.54/naxsi_src/ --user=nginx --group=nginx --with-pcre-jit --with-debug --with-ipv6 --with-http_ssl_module --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp chdir=/root/nginx-1.8.0
    - name: Compile nginx step 2
      command: make chdir=/root/nginx-1.8.0
    - name: Install nginx
      command: make install chdir=/root/nginx-1.8.0
    - name: Create cache directory
      file: path=/var/cache/nginx state=directory owner=nginx group=nginx mode=700
    - name: Copy nginx configuration file
      copy: src=../config_files/nginx.conf dest=/etc/nginx/nginx.conf
    - name: Copy naxsi core rules file
      copy: src=../config_files/naxsi_core.rules dest=/etc/nginx/naxsi_core.rules
    - name: Copy naxsi rules file
      copy: src=../config_files/naxsi.rules dest=/etc/nginx/naxsi.rules
    - name: Copy nginx sysconfig file
      copy: src=../config_files/sysconfig-nginx dest=/etc/sysconfig/nginx
    - name: Copy nginx init script
      copy: src=../config_files/init_nginx dest=/etc/init.d/nginx mode=0755
    - name: Add nginx service
      command: /sbin/chkconfig --add nginx
